print("My family member names:")
print("Mother - Marita")
print("Father - Giorgi")
print("Grandfather (Mom Side) - Amirani")
print("Grandmother (Mom Side) - Nato")
print("Grandomther (Dad Side) - Ciala")
print("Grandfather (Dad Side) - Davit")
print("Brother - Nikoloz")
print("Uncle - Levani")
print("")